name: Docker Image CI

on:
  schedule:
      - cron: "0 4 * * *"  # Runs every day at 4 AM UTC = 9 AM in cairo
  workflow_dispatch:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: events-api-image
      IMAGE_TAG: ${{ github.run_number }} # or use `IMAGE_TAG: latest` if you want
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or any version you need
  # Run the scraper
      - name: Install Node.js dependencies
        run: npm install

      - name: Run scraper
        run: node web-scraper.js
        # only run during cron
        if: github.event_name == 'schedule'

# Build and push docker img
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag the image
        run: docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG


